# yaml-language-server: $schema=./schema.json
session: houston
root: '~/dev/houston'
windows:
  - name: backend
    root: ~/dev/houston
    panes:
      - commands: []
    commands:
      - vim

  - name: frontend
    root: ~/dev/houston/assets
    panes:
      - commands: []
    commands:
      - vim

  - name: server
    root: ~/dev/houston
    commands:
      - mix start

  - name: tunnel
    root: ~/dev/houston
    commands: []
