[tools]

"cargo:lolcrab" = "latest"
"pipx:codespell" = "2"
committed = "latest"
lefthook = "latest"
lua-language-server = "2"
node = "22"
pnpm = "latest"
ripgrep = "latest"
ruby = "3"
shellcheck = "0.10"
stylua = "2"
task = "latest"
yamllint = "1.35"

[settings]
experimental = true
disable_backends = ["asdf"]
