[tools]

"ubi:mazznoer/lolcrab" = "latest"
committed = "latest"
dprint = "latest"
lefthook = "latest"
lua-language-server = "2"
node = "22"
pnpm = "latest"
ripgrep = "latest"
shellcheck = "0.10"
stylua = "2"
task = "latest"
typos = "latest"
yamllint = "1.35"
"ubi:tamasfe/taplo" = "latest"

[settings]
experimental = true
disable_backends = ["asdf"]
