# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

cmd_duration.format = "[$duration]($style) "
aws.disabled = true

# language plugins
deno.disabled = true
docker_context.disabled = true
elixir.disabled = true
erlang.disabled = true
gcloud.disabled = true
lua.disabled = true
nodejs.disabled = true
package.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
sudo.disabled = false
bun.disabled = true

# to hide this from the prompt you can run kctx -u to unset the current context
[username]
format = "[$user]($style) "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[hostname]
format = "[$ssh_symbol$hostname]($style) "

[kubernetes]
disabled = false
style = "bright-blue"
