# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

elixir.disabled = true
nodejs.disabled = true
gcloud.disabled = true
ruby.disabled = true
docker_context.disabled = true
python.disabled = true
package.disabled = true
