[tools]

"cargo:ast-grep" = "latest"       # like grep but on code structure!
"cargo:erdtree" = "latest"        # file system tree visualizer with icons and git support
"cargo:eza" = "latest"            # ls replacement with icons and git support + more
"cargo:fastmod" = "latest"        # fast regex code modifications
"cargo:gping" = "latest"          # graph ping
"cargo:kdash" = "latest"          # kubernetes dashboard
"cargo:lolcrab" = "latest"        # like lolcat but in rust and with noise
"cargo:rnr" = "latest"            # A command-line tool to batch rename files and directories
"cargo:sd" = "latest"             # a modern alternative for sed with sensible defaults
"gem:tmuxinator" = "latest"       # tmux session manager
"npm:@commitlint/cli" = "latest"  # linter for checking that commits are following conventional commits
"npm:neovim" = "latest"           # support for javascript plugins in neovim
"npm:npkill" = "latest"           # easily find and delete heavy node modules
"npm:prettier" = "latest"         # code formatter (js, ts, json, yaml and more)
"npm:tldr" = "latest"             # useful usage instructions for CLI apps
"npm:trash-cli" = "latest"        # rm -> system trash (cross platform)
"ubi:joshmedeski/sesh" = "latest" # tmux session manager
"ubi:mr-karan/doggo" = "latest"   # DNS client (like dig but better)
bat = "latest"                    # modern `cat` with syntax highlighting
delta = "latest"                  # nicer git diffs
deno = "2"                        # Deno programming language
dust = "latest"                   # A more intuitive version of du in rust
elixir = "1.18.1-otp-27"          # Elixir programming language
erlang = "27"                     # Erlang programming language
fd = "latest"                     # modern `find`
fx = "latest"                     # like jq, but allows interactive exploration and copying paths
github-cli = "latest"             # GitHub CLI
go = "1"                          # Go programming language
gum = "latest"                    # CLI / scripting UI tools
helm = "latest"                   # install k8s packages
hyperfine = "latest"              # benchmarking tool
jless = "latest"                  # json explorer
jq = "latest"                     # pretty print and query json
kubectl = "latest"                # k8s cli
kubectx = "latest"                # switch between k8s clusters and namespaces quickly
lazydocker = "latest"             # docker TUI
lazygit = "latest"                # Git TUI
lua = "5"                         # Lua programming language
lua-language-server = "latest"    # Lua Language Server
neovim = "latest"                 # the best text editor/IDE
opentofu = "latest"               # terraform drop-in alternative, with more permissive license
pnpm = "latest"                   # better npm
python = "3.12"                   # Python programming language
rebar = "3.24.0"                  # build tool for Erlang (equivalent to mix in Elixir)
ripgrep = "latest"                # modern `grep`
ruby = "3"                        # Ruby programming language
rust = "1"                        # Rust programming language
starship = "latest"               # command prompt styling
stylua = "latest"                 # formatter for lua
task = "latest"                   # run tasks (modern make alternative)
uv = "latest"                     # install python packages
vivid = "latest"                  # generate color schemes for different tools
zoxide = "latest"                 # a modern version of autojump

[tools.node]
version = "22"
postinstall = 'corepack enable && corepack enable pnpm'

[settings]
# needed to enable ruby gems install
experimental = true
