[tools]
elixir = "1.18.1-otp-27"
go = "1"
erlang = "27.2"
lua = "5"
lazygit = "latest"
python = "3.12"
ruby = "3"
rebar = "3.24.0"
rust = "1"
deno = "2"
lua-language-server = "latest"

bat = "latest"                   # modern `cat` with syntax highlighting
fzf = "latest"                   # fuzzy finder
fd = "latest"                    # modern `find`
ripgrep = "latest"               # modern `grep`
github-cli = "latest"            # GitHub CLI
neovim = "latest"                # the best text editor/IDE
uv = "latest"                    # install python packages
kubectl = "latest"               # k8s cli
task = "latest"                  # run tasks (modern make alternative)
opentofu = "latest"              # terraform drop-in alternative, with more permissive license
lazydocker = "latest"            # docker TUI
jq = "latest"                    # pretty print and query json
fx = "latest"                    # like jq, but allows interactive exploration and copying paths
gum = "latest"                   # CLI / scripting UI tools
kubectx = "latest"               # switch between k8s clusters and namespaces quickly
helm = "latest"                  # install k8s packages
zoxide = "latest"                # a modern version of autojump
vivid = "latest"                 # generate color schemes for different tools
stylua = "latest"                # formatter for lua
"cargo:sd" = "latest"            # a modern alternative for sed with sensible defaults
"cargo:rnr" = "latest"           # A command-line tool to batch rename files and directories
"cargo:lolcrab" = "latest"       # like lolcat but in rust and with noise
"cargo:kdash" = "latest"         # kubernetes dashboard
jless = "latest"                 # json explorer
hyperfine = "latest"             # benchmarking tool
delta = "latest"                 # nicer git diffs
"cargo:fastmod" = "latest"       # fast regex code modifications
"cargo:eza" = "latest"           # ls replacement with icons and git support + more
"cargo:erdtree" = "latest"       # file system tree visualizer with icons and git support
starship = "latest"              # command prompt styling
dust = "latest"                  # A more intuitive version of du in rust
"cargo:ast-grep" = "latest"      # like grep but on code structure!
"npm:trash-cli" = "latest"       # rm -> system trash (cross platform)
"npm:prettier" = "latest"        # code formatter (js, ts, json, yaml and more)
"npm:npkill" = "latest"          # easily find and delete heavy node modules
"npm:tldr" = "latest"            # useful usage instructions for CLI apps
"npm:neovim" = "latest"          # support for javascript plugins in neovim
"npm:@commitlint/cli" = "latest" # linter for checking that commits are following conventional commits


[tools.node]
version = "22"
postinstall = 'corepack enable && corepack enable pnpm'
