[tools]
elixir = "1.18.1-otp-27"
node = { version = "22", postinstall = 'corepack enable && corepack enable pnpm' }
go = "1"
erlang = "27.2"
lua = "5"
lazygit = "latest"
python = "3.12"
ruby = "3"
rebar = "3.24.0"
bat = "latest"
rust = "1"
deno = "2"
lua-language-server = "latest"
fzf = "latest"
fd = "latest"
ripgrep = "latest"
github-cli = "latest"
neovim = "latest"
uv = "latest"
kubectl = "latest"
task = "latest"
opentofu = "latest"
lazydocker = "latest"
jq = "latest"
fx = "latest"
gum = "latest"
kubectx = "latest"
helm = "latest"
